affiliate_tag: birdcamera-20
products:
- description: No plastic/wood, holds 1.12 lbs black oil sunflower seed, patented
    high-quality design, green finish for all yards.
  img_url: https://m.media-amazon.com/images/I/81L0Jpj0rEL._AC_SL1500_.jpg
  num_reviews: 3439
  price: '11.99'
  rating: '4.3'
  title: Perky-Pet Green Seed Ball Wild Bird Feeder
  url: https://www.amazon.com/dp/B002NC2AEM
- description: Tail prop suet feeder with eco-material, two-sided wire mesh, sturdy
    design, and easy cleaning. Holds various foods, ideal gift for bird lovers, and
    100% satisfaction guarantee.
  img_url: https://m.media-amazon.com/images/I/71zH3Dc2lfL._AC_SL1500_.jpg
  num_reviews: '81'
  price: '23.99'
  rating: '4.6'
  title: Kingsyard Recycled Plastic Suet Bird Feeder
  url: https://www.amazon.com/dp/B0B97FPT84
- description: High-nutrition wild bird food with Safflower, Peanuts, Sunflower, Millet
    for Grosbeaks, Cardinals & more. Compatible with various feeders, ensures frequent
    & longer visits. Made in USA.
  img_url: https://m.media-amazon.com/images/I/91GJUhL2RiL._AC_SL1500_.jpg
  num_reviews: 2135
  price: '17.99'
  rating: '4.5'
  title: Kaytee Wild Bird Ultimate Birder's Blend Food Seed
  url: https://www.amazon.com/dp/B07QYCJ1VV
- description: 4K 8MP outdoor security camera with wide viewing angle, PoE installation,
    smart IVS alerts, weatherproof housing, night vision, cloud backup, and multi-browser
    compatibility ensures safety and easy access.
  img_url: https://m.media-amazon.com/images/I/51BT4KpjIiS._AC_SL1500_.jpg
  num_reviews: '21'
  price: '199.99'
  rating: '4.3'
  title: Amcrest 4K Optical Zoom IP Camera
  url: https://www.amazon.com/dp/B097NRQK7L
- description: USA-made seed, loved by Cardinals/songbirds, high-quality grains, in
    gourmet mixes, disliked by most squirrels.
  img_url: https://m.media-amazon.com/images/I/9142TTyKo5L._AC_SL1500_.jpg
  num_reviews: '11151'
  price: '11.98'
  rating: '4.6'
  title: Wagner's Safflower Seed Wild Bird Food
  url: https://www.amazon.com/dp/B004477AOO
- description: This item includes a tray for easy Kaytee Feeder station placement,
    allows for mess-free filling with refrigerated/frozen suet, and is suitable for
    year-round feeding.
  img_url: https://m.media-amazon.com/images/I/81TeER2BfPL._AC_SL1500_.jpg
  num_reviews: '533'
  price: '2.49'
  rating: '4.5'
  title: Kaytee Wild Berry High Energy Bird Suet, 11.75 Oz
  url: https://www.amazon.com/dp/B005AU6EKA
- description: Premium cedar birdhouse with rust-free stainless-steel hardware, offering
    maximum ventilation, easy cleaning, blowfly management, predator protection, and
    fledgling support.
  img_url: https://m.media-amazon.com/images/I/61Jmu33ukJL._AC_SL1500_.jpg
  num_reviews: '4584'
  price: '27.98'
  rating: '4.7'
  title: Nature's Way Bird Products CWH3 Cedar Bluebird Box House
  url: https://www.amazon.com/dp/B00BYTRWZM
- description: This cedar feeder holds 3 lbs of mixed seed, features a removable powder-coated
    metal screen for drainage, and is compatible with Woodlink's pole or post mounting
    systems (sold separately). Made in the USA.
  img_url: https://m.media-amazon.com/images/I/71DQe7ckZ8L._AC_SL1500_.jpg
  num_reviews: '727'
  price: '51.80'
  rating: '4.6'
  title: Woodlink 3 in 1 Platform Bird Feeder
  url: https://www.amazon.com/dp/B003ZUHL2W
- description: Accommodates multiple birds with 6 flower-shaped ports; built-in bee
    guards and ant moat; wide-mouth bottle for easy, mess-free filling; easy to clean;
    30 oz capacity.
  img_url: https://m.media-amazon.com/images/I/719JwRNsUDL._AC_SL1500_.jpg
  num_reviews: '3764'
  price: '17.47'
  rating: '4.6'
  title: "Perky-Pet 209B-1SR Our Best Glass Hummingbird Feeder with Perches, Built-in\
    \ Ant Moat and Bee Guards - 30 oz Outdoor Garden D\xE9cor Hummingbird Feeder"
  url: https://www.amazon.com/dp/B00GSQBYNC
- description: Multifunctional small hummingbird feeder with clip design for various
    placements. Lightweight, affordable plastic with easy cleaning. Vibrant red flower
    design attracts birds. Unique, bee-resistant design. Great garden gift for bird
    lovers.
  img_url: https://m.media-amazon.com/images/I/61FOln+NS6L._AC_SL1500_.jpg
  num_reviews: '166'
  price: '12.95'
  rating: '4.4'
  title: PiiSheou 4 Pack Handheld Hummingbird Feeders, Mini Plastic Window Hummingbird
    Feeders with Clips for Hummingbird House,Flowerpot,Tree Branch
  url: https://www.amazon.com/dp/B09GMK5TH1
- description: Our Sunflower seed attracts various songbirds, providing high oil,
    protein, and energy for year-round feeding. Processed in a USDA & BRC-GS approved
    facility, meeting quality standards.
  img_url: https://m.media-amazon.com/images/I/71o58E2lZvL._AC_SL1500_.jpg
  num_reviews: '122'
  price: '18.98'
  rating: '4.6'
  title: Happy Wings Black Oil Sunflower Bird Food, 5 Pounds | No Grow Seed | Bird
    Seed for Wild Birds
  url: https://www.amazon.com/dp/B09Y5SGZPG
- description: Introducing a versatile, eco-friendly, and durable product with an
    innovative design for multi-purpose use and long-lasting performance. Perfect
    for everyday needs.
  img_url: https://m.media-amazon.com/images/I/71vABpHG3fL._AC_SL1500_.jpg
  num_reviews: '599'
  price: '17.98'
  rating: '4.6'
  title: Happy Wings Nyjer/Thistle Seeds Wild Bird Food - 5 Pounds I No Grow Seed
    I Bird Seed for Wild Birds
  url: https://www.amazon.com/dp/B09CH5XJCD
- description: Eco-friendly recycled poly lumber bird feeder; crack/fade resistant;
    vinyl coated wire for bird safety; easy-access peanuts; attracts various bird
    species; blends with nature.
  img_url: https://m.media-amazon.com/images/I/61qqTyUHutL._AC_SL1500_.jpg
  num_reviews: '34'
  price: '53.15'
  rating: '4.5'
  title: JCs Wildlife Poly Lumber Hanging Whole Peanut Feeder (Green and Tan)
  url: https://www.amazon.com/dp/B073FQMQZM
- description: USDA-inspected, chemical-free, raw Virginia peanuts ideal for boiling,
    roasting, or frying. Perfect for human consumption or attracting various wildlife.
    Delivered in sealed box; satisfaction guaranteed.
  img_url: https://m.media-amazon.com/images/I/81LWPRb4EtL._SL1500_.jpg
  num_reviews: '1702'
  price: '14.98'
  rating: '4.6'
  title: Sky | Premium USA Grown, Raw Peanuts in Shell for Squirrels, 2.5lb | Unsalted
    Peanuts in The Shell
  url: https://www.amazon.com/dp/B08TM6MJB4
- description: Bird Feeding Station Kit includes squirrel baffle, adjustable hooks,
    wire mesh tray, and plastic water bowl for versatile bird attraction. Features
    a vintage look and makes a thoughtful gift. Customer satisfaction guaranteed.
  img_url: https://m.media-amazon.com/images/I/6103OSNE6FL._AC_SL1500_.jpg
  num_reviews: '354'
  price: '55.99'
  rating: '4.4'
  title: Bird Feeding Station Kit Bird Feeder Pole Wild Bird Feeder Hanging Kit with
    Suet Cage Bird Bath Mesh Tray Fruit Hook Double W Hook for Attracting Wild Birds
    and Planter Hanger Lights
  url: https://www.amazon.com/dp/B093B3PYQK
- description: Watch birds on your phone with NETVUE's smart bird feeder camera featuring
    1080P color night vision and a bird-friendly design. Ideal gift for families,
    allowing sharing within a bird lover community.
  img_url: https://m.media-amazon.com/images/I/71znFnokX3L._AC_SL1500_.jpg
  num_reviews: '284'
  price: '224.99'
  rating: '4.3'
  title: NETVUE Birdfy Lite- Smart Bird Feeder Camera with Solar Pannel, Bird Watching
    Camera Auto Capture Bird Videos & Motion Detection
  url: https://www.amazon.com/dp/B0BWDY2PXY
- description: Premium quality metal deck rail bird bath with rust-proof clamp, adjustable
    for decks up to 2 inches thick. Easy installation and cleaning, attracts various
    bird species, and can also be used as a feeder.
  img_url: https://m.media-amazon.com/images/I/81FsiQHBxtL._AC_SL1500_.jpg
  num_reviews: '93'
  price: '25.98'
  rating: '4.3'
  title: DREAMSOUL Deck Mounted Bird Bath Metal Birdbath Bowl
  url: https://www.amazon.com/dp/B0B2JF2BSV
- description: Upgrade your yard with this stable, easy-to-assemble peacock glass
    birdbath. Attracts birds, aerates soil, and beautifies outdoor space. Durable,
    waterproof, handcrafted with stainless metal stake.
  img_url: https://m.media-amazon.com/images/I/611M5D0Ql7S._AC_SL1500_.jpg
  num_reviews: '1598'
  price: '30.99'
  rating: '4.1'
  title: MUMTOP Glass Bird Bath, Garden Outdoor Birdbaths Birdfeeder with Metal Stake
    Peacock
  url: https://www.amazon.com/dp/B085XK3R3S
- description: Hanizi deck mounted birdbath provides drinking and bathing water for
    garden birds for nature enthusiasts.
  img_url: https://m.media-amazon.com/images/I/91NmCH7jsdL._AC_SL1500_.jpg
  num_reviews: '3081'
  price: '19.99'
  rating: '4.5'
  title: Hanizi Bird Bath Deck Mounted Bowl 12 Inches, Balcony Railing Birdbaths Unheated
  url: https://www.amazon.com/dp/B08HDFP6GP
- description: Watch birds on your phone with the NETVUE smart bird feeder, featuring
    a 1080p camera, 8x magnification, and real-time notifications. Auto-captures and
    stores images/videos for easy sharing, and connects to a worldwide bird-lover
    community. Ideal gift for families.
  img_url: https://m.media-amazon.com/images/I/715R+B5XxhL._AC_SL1500_.jpg
  num_reviews: '40'
  price: '174.99'
  rating: '4.5'
  title: NETVUE Birdfy Lite - Smart Bird Feeder Camera, Bird Watching Camera, Auto
    Notify When Birds Detected, Bird House with Camera Wireless WiFi (Solar Camera
    Lite)
  url: https://www.amazon.com/dp/B09ZV69HT9
